### ISSUE TITLE
Add plugin for Notepad++

### ISSUE THREAD

**Issue by devomaa** [SquidDev/illuaminate#13]

**Comment by SquidDev** [comment]
I'm afraid I've no plans to add Notepad++ integration. We're using LSP, which should allow us to work with [most editors](https://microsoft.github.io/language-server-protocol/implementors/tools/). However, it appears that Nodepad++ does not support this.

There's clearly talk about adding it (notepad-plus-plus/notepad-plus-plus#4440), but I'm afraid it's not something I want to do on my end. It's a large project, and I don't personally use N++.
