### ISSUE TITLE
Adding HTML to generated documentation head?

### ISSUE THREAD

**Issue by MCJack123** [SquidDev/illuaminate#20]
I want to add some social information to [a certain website generated with illuaminate](https://tweaked.cc) by adding a few `meta` tags to the `head` of the generated HTML. However, I can't find a configuration option in the default config to insert custom HTML. Is this currently possible? And if not, would it be possible to add this in? This would be real helpful not only for adding metadata, but also for adding additional external scripts and stylesheets (though these can already be added locally), among other things I'm probably forgetting.

**Comment by SquidDev** [comment]
Just curious as to what sort of metadata you'd want to provide? It might be sensible to bake some of it into the default template. And if not, don't know if there's any more advanced templating functionality we'd need to provide (variable substitution, etc...) to facilitate it.

**Comment by MCJack123** [comment]
I'm mainly looking at the `og:` tags, and possibly the `twitter:` tags as well. `og:site_name`, `og:title`, and `og:description` are the important ones, and `og:image`, `og:url`, and `twitter:*` will be useful too, though not as important. For Discord in particular, the `theme_color` name tag would also be helpful to set the color of the sidebar that appears in embeds. In addition, being able to set favicon paths (instead of relying on `/favicon.ico` existing) might be a good thing to have.

**Comment by SquidDev** [comment]
![tweaked.cc embedded in Discord](https://user-images.githubusercontent.com/4346137/103235474-33262200-493a-11eb-9527-bdfeda6ee2a1.png)

Better? I'm not 100% happy with the implementation right now, but Discord and Twitter seem happy with it at least.
