### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by Lupus590** [SquidDev/illuaminate#22]
The prebuild link for windows in the readme is dead (404) and I can't build from source as my ISP blocks the git protocol (yes they are the same stupid ISP that is blocking madefor.cc) so easy can't fetch dependencies.

Getting the dependencies via https should work but I don't know what I need to change to do that.

**Comment by SquidDev** [comment]
Ahh, sorry! The download link should be https://squiddev.cc/illuaminate/windows-x86-64/illuaminate.exe That's one silly copy-and-paste error.

Ahh, classic Virgin Media. It might be worth switching your DNS to a non-Virgin one (e.g. 1.1.1.1 or 8.8.8.8) - not sure whether that'd work for protocol-level blocks though. Or try to convince the account owner to whitelist GitHub and whoever else.
