### ISSUE TITLE
Code blocks in markdown documents are displayed incorrectly.

### ISSUE THREAD

**Issue by SkyTheCodeMaster** [SquidDev/illuaminate#28]
I have a codeblock in a markdown on my [SkyDocs](https://skydocs.madefor.cc/articles/Installer.html) website, and instead of it being in a normal looking codeblock, (pictured below)
![image](https://user-images.githubusercontent.com/34724753/122439085-533db200-cf69-11eb-8738-06f1ab1e8de5.png)
It gets shrunken down into a single line, (pictured below)
![image](https://user-images.githubusercontent.com/34724753/122439161-681a4580-cf69-11eb-801a-773e7944dedb.png)
If you open up the html of the website, the `<code></code>` block does have multiple lines, so it's possible a CSS issue.
![image](https://user-images.githubusercontent.com/34724753/122439252-7c5e4280-cf69-11eb-8ab9-1be4f9df55ee.png)
In [the Timer event on CC:T documentation](https://tweaked.cc/event/timer.html), the code block appears exactly as it does [in the markdown](https://github.com/SquidDev-CC/CC-Tweaked/blob/mc-1.15.x/doc/events/timer.md)
![image](https://user-images.githubusercontent.com/34724753/122439548-bc252a00-cf69-11eb-87a9-094cd4f3fc09.png)
![image](https://user-images.githubusercontent.com/34724753/122439569-c2b3a180-cf69-11eb-9b78-f0da7a3f4f21.png)

**Comment by SkyTheCodeMaster** [comment]
So I went into my [SkyOS Desktop](https://skydocs.madefor.cc/articles/SkyOS%20Desktop.html) article, and it's codeblock is very white.
![image](https://user-images.githubusercontent.com/34724753/122479579-5355a600-cf99-11eb-869c-a4718ec7f561.png)
[The markdown](https://github.com/SkyTheCodeMaster/SkyDocs/blob/main/src/main/articles/desktop.md) is here.

**Comment by SquidDev** [comment]
The code block issue is a problem with our markdown parser. A good-enough work around is to trim any trailing whitespace in your file - that appears to fix it for me.

The styling issue is due to your custom CSS. You either need to update the `pre.highlight.highlight-lua` rule to match CC:T's, or just remove the `styles` and `scripts` tags from your illuaminate.sexp file.
