### ISSUE TITLE
EXE flagged by Windows Defender.

### ISSUE THREAD

**Issue by Lupus590** [SquidDev/illuaminate#30]
I just downloaded the Windows build from the website and Windows Defender popped up with this.
![image](https://user-images.githubusercontent.com/9790321/143680218-f7bf864f-3183-47b2-b320-2d8ea38f9b2a.png)
I assume that it's a false positive but it's probably something to be aware of anyway. Either way, I'm going to avoid using the new EXE until I hear from you.

**Comment by SquidDev** [comment]
Assuming the sha256 sum is 244302fbd82d8385daadf0e26618557237a863a0507ddbe830b19a7741d3daa2, it should be safe. My understanding is just that Windows defender doesn't like UPX - maybe I should stop using it and just start shipping the chunky exes :(.

**Comment by Lupus590** [comment]
How impractical is having two builds? Then those who have issues can choose the big one instead.
