### ISSUE TITLE
LSP server is broken

### ISSUE THREAD

**Issue by SquidDev** [SquidDev/illuaminate#32]
It now just exits immediately. We should probably try to merge in the latest commits from upstream and work _something_ out.

**Comment by tomodachi94** [comment]
Any updates on this?

**Comment by SquidDev** [comment]
Alas, no. I stopped publishing builds in 8873299947dff0b08110c7fa43972797aa75f6ab, but forgot to remove to remove mention of it from the README. Will do so.

**Comment by tomodachi94** [comment]
Ah okay, thank you! :)
