### ISSUE TITLE
ignore format:table-trailing

### ISSUE THREAD

**Issue by Commandcracker** [SquidDev/illuaminate#34]
is there a way to ignore format:table-trailing ?

i would like to lint something like this without warnings
```lua
local foo = {
    bar = "foo",
    foo = "bar"
}
```

![image](https://user-images.githubusercontent.com/49335821/176894398-984a8ca8-76a6-42b3-b17a-b741e7d814be.png)

**Comment by SquidDev** [comment]
You can enable/disable linters inside the `illuaminate.sexp` section. [CC:T's](https://github.com/cc-tweaked/CC-Tweaked/blob/mc-1.16.x/illuaminate.sexp) is probably the most complete example, but in your case you'd want something like this:

```lisp
(at /
  (linters -format:table-trailing))
```
