### ISSUE TITLE
[Feature-Request] Musl libc builds

### ISSUE THREAD

**Issue by Commandcracker** [SquidDev/illuaminate#37]
Musl libc builds for distros like Alpine Linux.

**Comment by SquidDev** [comment]
Huh! Historically builds used to be statically linked, but apparently I broke that back in March. The versioned builds (i.e. https://squiddev.cc/illuaminate/bin/0.1.0-7-g2a5a89c/illuaminate-linux-x86_64) _are_ statically linked, so do work on Alpine.

I will update the README to link to these newer files, suspect I need some magic to redirect to the latest version.
