### ISSUE TITLE
Latest build referencing invalid commit ID

### ISSUE THREAD

**Issue by Commandcracker** [SquidDev/illuaminate#38]
https://squiddev.cc/illuaminate/bin/latest/illuaminate-linux-x86_64
illuaminate 0.1.0-7-[g2a5a89c](https://github.com/SquidDev/illuaminate/commit/g2a5a89c)

https://squiddev.cc/illuaminate/linux-x86-64/illuaminate
illuaminate [353a1e3](https://github.com/SquidDev/illuaminate/commit/353a1e3)

**Comment by SquidDev** [comment]
The `g` should be ignored: it's referencing https://github.com/SquidDev/illuaminate/commit/2a5a89c.
