### ISSUE TITLE
Having illuaminate copy over images

### ISSUE THREAD

**Issue by 9551-Dev** [SquidDev/illuaminate#49]
Hi, would there be a sane way to have illuaminate move over images reference in MD files?

right now if you have an image and an md file in the same folder (and you reference that image in the md file) illuaminate will generate the html for that image but it wont actually copy over the image, i was thinking if it would be possible for illuaminate to make copies of all images which it could then reference in the html in some way (maybe there is a better/easier way to do this but i am not aware of it)

**Comment by SquidDev** [comment]
Thanks for the suggestion! I've been meaning to do this for ages - it would be useful in CC:T too - but keep forgetting.

Added in f294ab2ce6f66827245d398fd7093a7eb6b48d10.

**Comment by SquidDev** [comment]
Well, has been added, but looks like CI is failing right now D:. Gah, I love you OCaml, but multi-platform builds are the worst.

**Comment by SquidDev** [comment]
Kicked off a rebuild, that should be published now.
